### ISSUE TITLE
Improvement: Increase the width of the main text window in sphinx-needs layout

### ISSUE THREAD

**Issue by antonkri** [eclipse-score/score#51]
> [!IMPORTANT]
> Make sure to link this issue with the PR for your improvement.

Currently the part in the middle of the window with the main text is not sufficient wide and the left part is too large. Please adapt the layout, that the left part gets smaller and the one in the middle larger.

![Image](https://github.com/user-attachments/assets/1d681645-31f2-4cf6-a05d-1476fbdaf065)

**Comment by danwos** [comment]
I made some tests with different widths. Here are the results:

#### 1. width=88rem (default)
![Image](https://github.com/user-attachments/assets/a9b685c4-f5ba-4de4-87fc-4f096c66867d)

#### 2. width= 100rem
![Image](https://github.com/user-attachments/assets/a809182a-018b-4489-9f1c-da53af343c2b)

#### 3. width= 100rem + optimized left sidebar (less width, 20% instead of 25%)
Less sidebar is not possible, as SCORE has some long titles and especially subtitles get intended and take therefore even more space.
The only problem here, the top-navbar is not aligned with the content area. Fix is doable, but not so easy.
![Image](https://github.com/user-attachments/assets/3da060fd-e4a9-4274-b1e5-4819d6d4d169)

#### 4. fullscreen: width=100% + optimized left sidebar
![Image](https://github.com/user-attachments/assets/2a729b5f-10e7-42e5-bf61-365a2ddf32f7)

I like option 3. most. The fullscreen (option 4) looks good, but the text is really hard to read/follow on my QHD monitor.

I will prepare a PR with option 3.
